### PR TITLE
Visual diff: trigger `DOM_CHANGED` event after enable/disable

### LINKED ISSUE #460: Passing `?readthedocs-diff=true` breaks Links Preview
Steps to reproduce:
1. Go to https://docs--11751.org.readthedocs.build/en/11751/user-defined-redirects.html?readthedocs-diff=true
2. Hover on "custom domains" under "Root URL redirect at /" section
3. No preview is shown, and no error is reported

If you go to https://docs--11751.org.readthedocs.build/en/11751/user-defined-redirects.html (without `readthedocs-diff`), links preview works properly.

### PR DESCRIPTION
**Pull request by humitos**
A new event `READTHEDOCS_ROOT_DOM_CHANGED` is triggered when the "Visual diff" is enabled/disabled after the DOM was modified.

This allows other addons to subscribe to this event to re-initialize if required. I used this event from links preview to call `setupTooltips` again to re-install tooltips on these links.

I migrated links preview to a `LitElement` to be able to make usage of this pattern and follow what we already had.

We will be able to do something similar on #157

Closes #460

### CODE REVIEW

File: src/events.js [hunk 1]
```diff
@@ -9,6 +9,8 @@ export const EVENT_READTHEDOCS_FLYOUT_SHOW = "readthedocs-flyout-show";
 export const EVENT_READTHEDOCS_FLYOUT_HIDE = "readthedocs-flyout-hide";
 export const EVENT_READTHEDOCS_ADDONS_DATA_READY =
   "readthedocs-addons-data-ready";
+export const EVENT_READTHEDOCS_ROOT_DOM_CHANGED =
```
Comment (ericholscher) [inline src/events.js:12]: Should we have a docstring or similar to describe the events here?

**Review by ericholscher — APPROVED** [review]
Looks like a nice refactor to me.

File: src/events.js (hunk 1 above)
Comment (humitos) [reply src/events.js:27]: Added 👍🏼
